baseURL = "https://duclassical.mrph.dev/"
languageCode = "en-us"
title = "DU Classical Society"


[menu]
# -------------------------
  [[menu.bot]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/8bdSVaTkr8"
    pre = "fab fa-discord"

  [[menu.bot]]
    identifier = "facebook"
    name = "Facebook"
    url = "https://www.facebook.com/DUClassics"
    pre = "fab fa-facebook"

  [[menu.bot]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/duclassical/"
    pre = "fab fa-instagram"

  [[menu.bot]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/DUClassical"
    pre = "fab fa-twitter"

  
