backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  media_folder: static/img
# public_folder: /img
media_library:
  name: uploadcare
  config:
    publicKey: 45b23e70f2f704125f07
    crop: "3:2, 900:400, 1:1"


collections:
  - name: 'slider'
    label: 'Main Slider'
    folder: 'content/main'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Alt', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }

  - name: 'events'
    label: 'Events'
    folder: 'content/events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Event', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Event Date', name: 'date', widget: 'datetime' }
      - { label: "Upcoming", name: "upcoming", widget: "boolean", default: true}
      - { label: "Repeating", name: "repeating", widget: "boolean", default: false}
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'committee'
    label: 'Committee'
    folder: 'content/committee'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Date (for sorting)', name: 'date', widget: 'datetime' }
      - { label: 'Email Prefix', name: 'short', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Twitter',name: 'twitter', widget: 'string',required: false}
      - { label: 'Insta',name: 'insta', widget: 'string',required: false}
      - { label: 'Facebook', name: 'facebook', widget: 'string',required: false}
      - { label: 'Website', name: 'site', widget: 'string', required: false}
  
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'guide'
    label: 'Guide'
    folder: 'content/guide'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown'}
    
      