name: Manual workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  crypt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Encrypt index
      run: sshpass -p ${{ secrets.NETSOCCONT }} ssh -tt -o UserKnownHostsFile=/dev/null root@mrph.netsoc.ie -p 51150
    - name: Do stuff
      run: |
        rm -r /var/www/html/*
        git clone https://github.com/Jack-alope/du-classical-site.git
        cd du-classical-site
        hugo
        mv -v public/* /var/www/html
